INSERT INTO categories (name, code) VALUES
('Eletrônicos', 'ELE'),
('Roupas', 'ROU'),
('Cosméticos', 'COS'),
('Livros', 'LIV'),
('Alimentos', 'ALI'),
('Brinquedos', 'BRI'),
('Ferramentas', 'FER'),
('Móveis', 'MOV'),
('Artigos Esportivos', 'ESP'),
('Produtos de Limpeza', 'LIM'),
('Acessórios de Moda', 'MOD'),
('Instrumentos Musicais', 'MUS'),
('Artigos de Decoração', 'DEC'),
('Produtos para Animais', 'ANI'),
('Material de Escritório', 'ESC'),
('Equipamentos de Academia', 'ACA'),
('Artigos de Papelaria', 'PAP'),
('Utensílios Domésticos', 'DOM'),
('Produtos para Jardim', 'JAR'),
('Suplementos Alimentares', 'SUP');


INSERT INTO products (name, code, price, quantity, ean, category_id, manufacturer) VALUES
('Smartphone Samsung Galaxy S20', 'SSG-S20', 999.99, 50, '1234567890123', 1, 'Samsung'),
('Camiseta Masculina Branca', 'CAM-BRA', 19.99, 100, NULL, 2, 'Marca X'),
('Shampoo Anticaspa', 'SH-ANT', 9.99, 200, NULL, 3, 'Marca Y'),
('Livro - O Senhor dos Anéis', 'LIV-SDA', 29.99, 30, '9788578270697', 4, 'Editora Z'),
('Arroz Integral 1kg', 'ARZ-INT', 4.99, 150, NULL, 5, 'Marca A'),
('Boneca Barbie', 'BARBIE', 24.99, 80, NULL, 6, 'Mattel'),
('Furadeira Elétrica 500W', 'FUR-500', 49.99, 50, NULL, 7, 'Marca B'),
('Sofá de Couro', 'SOF-COU', 699.99, 20, NULL, 8, 'Marca C'),
('Bola de Futebol Oficial', 'BOL-FUT', 19.99, 40, NULL, 9, 'Nike'),
('Detergente Líquido', 'DET-LIQ', 3.99, 100, NULL, 10, 'Marca D'),
('Óculos de Sol', 'OCL-SOL', 39.99, 60, NULL, 11, 'Marca E'),
('Violão Acústico', 'VIO-ACU', 149.99, 15, NULL, 12, 'Marca F'),
('Vaso Decorativo', 'VAS-DEC', 14.99, 70, NULL, 13, 'Marca G'),
('Ração para Cães Adultos', 'RAC-CAA', 29.99, 90, NULL, 14, 'Marca H'),
('Caneta Esferográfica Azul', 'CAN-AZ', 0.99, 500, NULL, 15, 'Marca I'),
('Esteira Ergométrica', 'EST-ERG', 299.99, 10, NULL, 16, 'Marca J'),
('Caderno Universitário', 'CAD-UNI', 5.99, 200, NULL, 17, 'Marca K'),
('Panela de Pressão', 'PAN-PRE', 29.99, 30, NULL, 18, 'Marca L'),
('Adubo Orgânico', 'ADU-ORG', 7.99, 120, NULL, 19, 'Marca M'),
('Whey Protein', 'WHEY', 39.99, 80, NULL, 20, 'Marca N');
